### ISSUE TITLE
[Epic] Pod privileged: tag 1.0.0 release

### ISSUE THREAD

**Issue by flavio** [kubewarden/pod-privileged-policy#149]
Tag v1.0.0 of this policy. As part of that, we want to test the changes requested by [this](https://github.com/kubewarden/kubewarden-controller/issues/839) issue.

If everything works as expected, we will propagate the same changes to all our policies.

## Admission criteria

- [x] Enable automerge for dependency updates (minor and patch ones)
- [x] Enable release-drafter in policies and policy templates (e.g: [config](https://github.com/kubewarden/cel-policy/blob/main/.github/release-drafter.yml) + [workflow](https://github.com/kubewarden/cel-policy/blob/main/.github/workflows/release-drafter.yml)).
- [x] Update reusable-release-policy-X workflows in kubewarden/github-actions to publish the already present draft GH release (e.g [here](https://github.com/kubewarden/cel-policy/blob/main/.github/workflows/release.yml#L41-L45)).
- [x] Investigate which [OCI metadata annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) are useful, as they can be[ consumed by ArtifactHub](https://artifacthub.io/docs/topics/repositories/container-images/) and Renovatebot:
  The only needed annotation is `org.opencontainers.image.source`.
- [ ] #178

**Comment by flavio** [comment]
Marking this epic as done, for 1.21 we don't plan to implement the changes required to address https://github.com/kubewarden/pod-privileged-policy/issues/178
